<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Testriq-L17" name="com.qa.IgniteTestcases.HelpPage_TestRailTest" tests="2" failures="1" timestamp="03 Jun 2020 10:47:31 GMT" time="25.421" errors="0">
  <testcase name="clickOnDefaultLocationAndGeostixAutomation" time="15.171" classname="com.qa.IgniteTestcases.HelpPage_TestRailTest"/>
  <testcase name="C815_VerifyClickon_HelpTab" time="10.250" classname="com.qa.IgniteTestcases.HelpPage_TestRailTest">
    <failure type="java.lang.AssertionError" message="expected [http://help.brandify.com/help/] but found [http://help.brandify.com/help]">
      <![CDATA[java.lang.AssertionError: expected [http://help.brandify.com/help/] but found [http://help.brandify.com/help]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.IgnitePages.HelpPage_TestRail.C815_VerifyClickon_HelpTab(HelpPage_TestRail.java:37)
at com.qa.IgniteTestcases.HelpPage_TestRailTest.C815_VerifyClickon_HelpTab(HelpPage_TestRailTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- C815_VerifyClickon_HelpTab -->
</testsuite> <!-- com.qa.IgniteTestcases.HelpPage_TestRailTest -->
