<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-Q9J1O2G" name="com.b1.qa.testcases.ReviewTexts" tests="4" failures="0" timestamp="14 Mar 2019 11:15:36 GMT" time="18.636" errors="1">
  <testcase name="ReviewsPageSetup" time="12.376" classname="com.b1.qa.testcases.ReviewTexts"/>
  <testcase name="verifyReviewText2" time="6.260" classname="com.b1.qa.testcases.ReviewTexts">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 19, Size: 19">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 19, Size: 19
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.b1.qa.testcases.ReviewTexts.verifyReviewText2(ReviewTexts.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyReviewText2 -->
  <testcase name="verifyReviewText1" classname="com.b1.qa.testcases.ReviewTexts">
    <skipped/>
  </testcase> <!-- verifyReviewText1 -->
  <testcase name="verifyReviewText" classname="com.b1.qa.testcases.ReviewTexts">
    <skipped/>
  </testcase> <!-- verifyReviewText -->
</testsuite> <!-- com.b1.qa.testcases.ReviewTexts -->
